parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  es6: true
  browser: true
  node: true
plugins:
  - prettier
  - react
  - react-hooks
extends:
  - plugin:prettier/recommended
  - eslint:recommended
  - plugin:react/recommended
  - react-app
rules:
  no-console: warn
  no-eval: error
  prettier/prettier: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  'react/prop-types': [2, { ignore: ['children'] }]
settings:
  react:
    version: detect
